export const CATEGORY_ACTION_TYPES = {
    SET_CATEGORY_START: 'category/SET_CATEGORY_START',
    SET_CATEGORY_SUCCESS: 'category/SET_CATEGORY_SUCCESS',
    SET_CATEGORY_FAILED: 'category/SET_CATEGORY_FAILED'
}